# Generated by Django 4.0.6 on 2022-07-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('principal_player', models.CharField(max_length=30)),
                ('creation_date', models.DateField(null=True)),
            ],
        ),
    ]
