# Generated by Django 4.0.6 on 2022-08-03 03:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasketballTeams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
