# Generated by Django 4.0.6 on 2022-08-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasketballTeams', '0005_remove_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
